# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
my_data = np.array([1,2,3,4,5,6,7])
np.size(my_data)

7

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
b = np.zeros(10)
b[4]=1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
c = np.arange(10,50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
d = np.arange(20)
d = d[::-1]
print(d)

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
e = np.arange(9).reshape(3,3)
print(e)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
f = np.eye(3)
print(f)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
g = np.random.random((3,3,3))
print(g)

[[[0.53548888 0.21961543 0.42337513]
  [0.59008418 0.40453362 0.16750286]
  [0.58700599 0.87328492 0.56332174]]

 [[0.32641015 0.31405926 0.45787865]
  [0.79989476 0.78548379 0.4155725 ]
  [0.80391093 0.30585522 0.48790527]]

 [[0.4726368  0.81237115 0.49117122]
  [0.95166407 0.58739349 0.16784503]
  [0.73148316 0.6207542  0.32053702]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
h = np.random.random((10,10))
hmin = h.min()
hmax = h.max()
print(hmin, hmax)

0.0007923170130764712 0.9962637241189543


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
k = np.random.random(30)
kmean = k.mean()
print(kmean)

0.4186437040152827


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
l = np.ones((5,5))
l[1:-1, 1:-1]=0
print(l)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [79]:
x = np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [81]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
m = np.diag(1 + np.arange(4),k=-1)
print(m)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
n = np.zeros((8,8),dtype=int)
n[1::2,::2] = 1
n[::2,1::2] = 1
print(n)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
p = np.unravel_index(100, (6,7,8))
print(p)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
q = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(q)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
r = np.random.random((5,5))
rmax, rmin = r.max(), r.min()
r = (r - rmin)/(rmax - rmin)
print(r)

[[0.38620348 0.04330015 0.00485454 0.45431698 0.32069393]
 [0.03490943 0.38903628 0.00159338 0.89813599 0.57393654]
 [0.82513676 1.         0.68886328 0.31341288 0.46481091]
 [0.12037496 0.77883079 0.         0.72096585 0.25266793]
 [0.1177594  0.71000739 0.28697571 0.97529902 0.92322179]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

<ipython-input-4-b9f1a6f5df9c>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
s = np.dot(np.ones((5,3)), np.ones((3,2)))
print(s)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
t = np.arange(11)
t[(3 < t) & (t <= 8)] *= -1

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [83]:

print(sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [88]:
z = np.array([1,2,3,4,5,6])
print(Z**Z)


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [89]:
z = np.array([1,2,3,4,5,6])
print(2 << Z >> 2)

[[0 0 0]
 [1 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [0 1 1]]


In [90]:
z = np.array([1,2,3,4,5,6])
print(Z <- Z)


[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]


In [91]:
z = np.array([1,2,3,4,5,6])
print(1j*Z)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+1.j]]


In [92]:
z = np.array([1,2,3,4,5,6])
print(Z/1/1)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 1.]]


In [93]:
z = np.array([1,2,3,4,5,6])
print(Z<Z>Z)

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [94]:
print(np.array(0) / np.array(0))

nan


<ipython-input-94-a69a51a14444>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))


In [95]:
print(np.array(0) // np.array(0))

0


<ipython-input-95-e29d1dbbd607>:1: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [96]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [4]:
u= np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(u)), u))

[-4. -3.  1.  5.  9.  3.  5. -6. -5. -9.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [97]:
a = np.array([2, 4, 7, 1, 4])
b = np.array([7, 2, 9, 0, 5])

c = np.intersect1d(a, b)
print(c)

[2 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [99]:
np.seterr(all="ignore")
Arr1 = np.array([1])
Arr2 = np.array([0])
result = Arr1 / Arr2
print(result)

[inf]


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [98]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


<ipython-input-98-c6ff0ad7fd7b>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [100]:
from datetime import datetime, timedelta

present = datetime.now() 
  
yesterday = present - timedelta(1)
  
tomorrow = present + timedelta(1)

print("Yesterday was = ", yesterday.strftime('%d-%m-%Y'))
print("Today is= ", present.strftime('%d-%m-%Y'))
print("Tomorrow is = ", tomorrow.strftime('%d-%m-%Y'))

Yesterday was =  20-01-2023
Today is=  21-01-2023
Tomorrow is =  22-01-2023


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [106]:
# dates of july  2020
print(np.arange('2016-07','2016-08', dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [107]:
A = np.ones(3)*1
B = np.ones(3)*2
print(np.add(A,B,out=B))
print(np.divide(A,2,out=A))
print(np.negative(A,out=A))
print(np.multiply(A,B,out=A))

[3. 3. 3.]
[0.5 0.5 0.5]
[-0.5 -0.5 -0.5]
[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x = np.random.uniform(0,10,10)
print (x - x%1)
print (np.floor(x))
print (np.ceil(x)-1)
print (x.astype(int))
print (np.trunc(x))

[6. 6. 6. 7. 2. 1. 8. 8. 3. 7.]
[6. 6. 6. 7. 2. 1. 8. 8. 3. 7.]
[6. 6. 6. 7. 2. 1. 8. 8. 3. 7.]
[6 6 6 7 2 1 8 8 3 7]
[6. 6. 6. 7. 2. 1. 8. 8. 3. 7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
y = np.zeros((5,5))
y += np.arange(5)
print(y)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
  for i in range(10):
    yield i
z = np.fromiter(generate(),dtype=int,count=-1)
print(z)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
a = np.linspace(0,1,12,endpoint=True)[1:-1]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
b = np.random.random(10)
b.sort()
print(b)

[0.06874177 0.11823347 0.26913951 0.36060069 0.58551975 0.58880901
 0.73527264 0.78672276 0.87603326 0.91127054]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
c = np.arange(10)
np.add.reduce(c)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
d = np.random.randint(0,5,5)
e = np.random.randint(0,5,5)
equal = np.allclose(d,e)
print(equal)


False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
f = np.zeros(10)
f.flags.writeable = False


In [ ]:
#checking if it is immutable
f[0]=1

ValueError: ignored

In [ ]:
#answer :  it is not immutable

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
g = np.random.random((10,2))
x = g[:,0]
y = g[:,1]
h = np.sqrt(x**2+y**2)
k = np.arctan2(y,x)
print(h)
print(k)


[1.2416087  0.80672867 0.97802263 0.88702931 0.80653646 0.55822504
 0.67544418 0.78951112 0.63593036 0.89638809]
[0.73968533 0.5386279  0.68628921 1.11998019 1.46320756 1.38533083
 0.43255878 1.21456726 0.62880512 0.35314511]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
l = np.random.random(10)
l[l.argmax()] = 0
print(l)

[0.42052099 0.72662141 0.778347   0.33750293 0.         0.751442
 0.61234511 0.18076855 0.46779254 0.72149564]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
m = np.zeros((5,5), [('x',float),('y',float)])
m['x'], m['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))

print(m)



[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [5]:
a = np.arange(10)
b = a + 0.5
c = 1.0 / np.subtract.outer(a, b)
print(np.linalg.det(c))

33961.93294480236


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [4]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [7]:
np.set_printoptions(threshold=float("inf"))
a = np.zeros((10,10))
print(a)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [8]:
a = np.arange(100)
b = np.random.uniform(0,100)
index = (np.abs(a-b)).argmin()
print(a[index])


24


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [8]:
a = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),
                   ('color', [ ('r', float, 1), ('g', float, 1),('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-8-dead18e6d453>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = np.zeros(10, [ ('position', [ ('x', float, 1),('y', float, 1)]),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [9]:
a = np.random.random((100,2))
X,Y = np.atleast_2d(a[:,0]), np.atleast_2d(a[:,1])
b = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(b)



[[0.         0.14008169 0.44638505 0.37428996 0.35370654 0.39942019
  0.55373937 0.57799332 0.53068266 0.54180024 0.41855121 0.36631979
  0.48147872 0.48862064 0.48574601 0.42035962 0.40440848 0.65688247
  0.41291606 0.41731701 0.49875793 0.39286753 0.46292577 0.39844442
  0.20571826 0.54653047 0.39372235 0.60554049 0.02100952 0.20526029
  0.37613148 0.4199608  0.6869859  0.41876198 0.56363739 0.6133488
  0.67778778 0.46073427 0.48232686 0.42931493 0.52687997 0.58354355
  0.21881235 0.40735612 0.47170429 0.47971966 0.40147426 0.44192652
  0.33969978 0.24731832 0.49489926 0.05687592 0.45839713 0.60922251
  0.46417613 0.28476736 0.54678401 0.55445656 0.51281305 0.2240827
  0.35502514 0.28189989 0.45140609 0.30741614 0.27638084 0.73024323
  0.34997399 0.31633644 0.60299383 0.31222301 0.53500786 0.4757983
  0.20375592 0.22451704 0.65983651 0.25583138 0.20407354 0.55970226
  0.33466684 0.62123708 0.45122859 0.3077506  0.4737142  0.68999724
  0.42983483 0.47781094 0.7554288  0.20682533 0.304

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [12]:
a= np.arange(10, dtype=np.float32)
b = a.astype(np.int32, copy=False)
print(a)
print(b)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [13]:
from io import StringIO

file = StringIO('''1, 2, 3, 4, 5
                   6,  ,  , 7, 8
                    ,  , 9,10,11''')
a = np.genfromtxt(file, delimiter=",", dtype=np.int)
print(a)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


<ipython-input-13-0ed594f6a046>:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.genfromtxt(file, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [14]:
a = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(a):
  print(index, value)
for index in np.ndindex(a.shape):
  print(index, a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [15]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
a = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
b = np.exp(-( (a-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(b)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [17]:
a = 10
b = 3
c = np.zeros((a,a))
np.put(c, np.random.choice(range(a*a), b, replace=False),1)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [17]:
a= np.array([[1,2,3,4,5],[6,7,8,9,0],[4,7,9,1,3]])
b = a - a.mean(axis=1, keepdims=True)
print(b)

[[-2.  -1.   0.   1.   2. ]
 [ 0.   1.   2.   3.  -6. ]
 [-0.8  2.2  4.2 -3.8 -1.8]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [20]:

a = np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])


[[8 7 4]
 [1 9 0]
 [7 3 9]]
[[7 3 9]
 [8 7 4]
 [1 9 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [21]:
a = np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())


False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [22]:
a = np.random.uniform(0,1,10)
b = 0.5
c = a.flat[np.abs(a - b).argmin()]
print(c)

0.44429489695581725


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [20]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)
c = np.nditer([a,b,None])
for x,y,z in c: z[...] = x + y
print(c.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [23]:
class NamedArray(np.ndarray):
  def __new__(cls, array, name="no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
  def __array_finalize__(self, obj):
    if obj is None: return
    self.info = getattr(obj, 'name', "no name")


a = NamedArray(np.arange(10), "range_10")
print (a.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [24]:
a = np.ones(10)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
print(a)


[3. 3. 2. 3. 5. 2. 2. 6. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [26]:
a = [1,2,3,4,5,6]
b = [2,3,9,5,3,1]
c = np.bincount(b,a)
print(c)


[0. 6. 1. 7. 0. 4. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [28]:
w,h  = 16,16
c = np.random.randint(0,2,(w,h,3)).astype(np.ubyte)
d = c[...,0]*256*256 + c[...,1]*256 +c[...,2]
n = len(np.unique(d))
print(np.unique(c))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [29]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[42 57 57 46]
 [57 40 47 38]
 [43 64 63 38]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [23]:
D = np.array([1,2,3,4,5])
S = np.array([5,6,7,8,9])
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[nan nan nan nan nan  1.  2.  3.  4.  5.]


<ipython-input-23-27e466fd943e>:5: RuntimeWarning: invalid value encountered in true_divide
  D_means = D_sums / D_counts


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [26]:
A = np.array([[1,2,3],[3,5,6],[5,7,8]])
B = np.array([[6,7,8],[1,2,6],[0,8,9]])
print(np.diag(np.dot(A, B)))


[  8  79 154]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [37]:
a = np.array([1,2,3,4,5])
b = 3
c = np.zeros(len(a) + (len(a)-1)*(b))
c[::b+1] = a
print(c)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [27]:
A = np.ones((5,5,3))
B = np.ones((5,5))
print(A * B[:,:,None])


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [40]:
a = np.arange(36).reshape(6,6)
a[[0,1]] = a[[1,0]]
print(a)

[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [41]:
a = np.random.randint(0,100,(10,3))
b = np.roll(a.repeat(2,axis=1),-1,axis=1)
b = b.reshape(len(b)*3,2)
b = np.sort(b,axis=1)
c = b.view( dtype=[('p0',b.dtype),('p1',b.dtype)] )
c = np.unique(c)
print(c)

[( 0, 29) ( 0, 87) ( 3, 32) ( 3, 44) ( 7, 21) ( 7, 85) ( 8, 40) ( 8, 98)
 ( 9, 59) ( 9, 87) (13, 27) (13, 61) (14, 21) (14, 88) (21, 85) (21, 88)
 (27, 61) (29, 87) (32, 44) (34, 78) (34, 83) (37, 42) (37, 74) (40, 98)
 (42, 74) (57, 73) (57, 95) (59, 87) (73, 95) (78, 83)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [43]:
C = np.bincount([1,1,2,3,4,4,6])
a = np.repeat(np.arange(len(C)), C)
print(a)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [45]:
def window_average(a, n=5) :
  c = np.cumsum(a, dtype=float)
  c[n:] = c[n:] - c[:-n]
  return c[n - 1:] / n
b = np.arange(20)
print(window_average(b, n=5))


[ 2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [46]:
from numpy.lib import stride_tricks
def rolling(a, window):
  shape = (a.size - window + 1, window)
  strides = (a.itemsize, a.itemsize)
  return stride_tricks.as_strided(a, shape=shape, strides=strides)
b = rolling(np.arange(10), 3)
print(b)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [34]:
arr = np.array([1.8,2.0,3.6,4,5,6])

print(np.logical_not(arr, out=arr))

print(np.negative(arr, out=arr))


[0. 0. 0. 0. 0. 0.]
[-0. -0. -0. -0. -0. -0.]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [53]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 1.42024761  9.96733958  3.65553034  2.06134757  0.0628401   8.46932781
   5.28799518  3.48237532  7.38557292  8.19980812]
 [ 5.71370421  9.26125024  3.36064289  0.29062823  4.51309489  6.67184739
   9.61470105  7.59648131  9.16850253 11.02825884]
 [ 1.11383339  4.06168104  2.536819    2.83940127  3.50321624  3.59918731
   4.81761853  1.39495692  0.57117522  1.70154398]
 [ 2.80664761  4.64084946 12.01869985  9.11194751 12.66491577  2.60388394
   0.613182   12.34524335 11.55152758 10.76262116]
 [ 2.54809453  7.47202968  0.64414277  1.04101449  5.76732053  7.48889728
   1.20351715  2.7428146   2.20331291  2.25771906]
 [ 8.48701686  4.10635248  1.73166568  4.81911124  4.82494318  1.56746248
  12.28201062  6.63778884  5.04458285  7.88795027]
 [ 3.10959911 11.32828784  5.24908154  2.74780483  2.70768057  9.13735914
   7.03488977  6.36234193  9.92703751 11.04514246]
 [ 4.14362272 11.4886996   4.67021411  4.86778908  5.37352304 11.30752731
   0.30251247  1.38244045  5.75585327  5.17542312]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [55]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[          1  8589934592           2 12884901888]
 [ 8589934592           2 12884901888           3]
 [          2 12884901888           3 17179869184]
 [12884901888           3 17179869184           4]
 [          3 17179869184           4 21474836480]
 [17179869184           4 21474836480           5]
 [          4 21474836480           5 25769803776]
 [21474836480           5 25769803776           6]
 [          5 25769803776           6 30064771072]
 [25769803776           6 30064771072           7]
 [          6 30064771072           7 34359738368]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [57]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)


10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [32]:

a= np.array([1,2,3,4,5,6,7,2,3,42,2,2,3,8,9])
print(np.bincount(a))
print(np.argmax(a))

[0 1 4 3 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 1]
9


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [63]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)


[[[[3 3 3]
   [0 0 3]
   [2 3 4]]

  [[3 3 4]
   [0 3 4]
   [3 4 0]]

  [[3 4 0]
   [3 4 0]
   [4 0 3]]

  [[4 0 0]
   [4 0 0]
   [0 3 3]]

  [[0 0 2]
   [0 0 1]
   [3 3 2]]

  [[0 2 4]
   [0 1 3]
   [3 2 0]]

  [[2 4 1]
   [1 3 4]
   [2 0 4]]

  [[4 1 3]
   [3 4 1]
   [0 4 3]]]


 [[[0 0 3]
   [2 3 4]
   [3 1 3]]

  [[0 3 4]
   [3 4 0]
   [1 3 4]]

  [[3 4 0]
   [4 0 3]
   [3 4 1]]

  [[4 0 0]
   [0 3 3]
   [4 1 4]]

  [[0 0 1]
   [3 3 2]
   [1 4 1]]

  [[0 1 3]
   [3 2 0]
   [4 1 3]]

  [[1 3 4]
   [2 0 4]
   [1 3 1]]

  [[3 4 1]
   [0 4 3]
   [3 1 0]]]


 [[[2 3 4]
   [3 1 3]
   [1 4 3]]

  [[3 4 0]
   [1 3 4]
   [4 3 0]]

  [[4 0 3]
   [3 4 1]
   [3 0 3]]

  [[0 3 3]
   [4 1 4]
   [0 3 3]]

  [[3 3 2]
   [1 4 1]
   [3 3 0]]

  [[3 2 0]
   [4 1 3]
   [3 0 1]]

  [[2 0 4]
   [1 3 1]
   [0 1 4]]

  [[0 4 3]
   [3 1 0]
   [1 4 3]]]


 [[[3 1 3]
   [1 4 3]
   [2 1 3]]

  [[1 3 4]
   [4 3 0]
   [1 3 4]]

  [[3 4 1]
   [3 0 3]
   [3 4 4]]

  [[4 1 4]
   [0 3 3]
   [4 4 2]]

  [[1 4 1]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [35]:
p, n = 5,10
a= np.ones((p,n,n))
b = np.ones((p,n,1))
c = np.tensordot(a, b, axes=[[0, 2], [0, 1]])
print(c)


[[50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]
 [50.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [40]:
a = np.ones((16,16))
b = 4
c = np.add.reduceat(np.add.reduceat(a, np.arange(0, a.shape[0], b), axis=0), np.arange(0, a.shape[1], b), axis=1)
print(c)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [41]:
a= np.arange(1000)
np.random.shuffle(a)
n = 5

print(a[np.argsort(a)[-n:]])

print(a[np.argpartition(-a,n)[:n]])

[995 996 997 998 999]
[998 999 997 996 995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [69]:
def cartesian(arrays):
  arrays = [np.asarray(a) for a in arrays]
  shape = (len(x) for x in arrays)
  ix = np.indices(shape, dtype=int)
  ix = ix.reshape(len(arrays), -1).T
  for n, arr in enumerate(arrays):
    ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]
 [3 0 0]
 [3 0 1]
 [3 1 0]
 [3 1 1]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [49]:
a = np.array([("numpy",6.2,7),("pandas", 2.4, 5)])
b= np.core.records.fromarrays(a.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(a)
print(b)


[['numpy' '6.2' '7']
 ['pandas' '2.4' '5']]
[(b'numpy', 6.2, 7) (b'pandas', 2.4, 5)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [50]:
a= np.random.randint(0,5,(10,3))
b = np.logical_and.reduce(a[:,1:] == a[:,:-1], axis=1)
c= a[~b]
print(a)
print(c)


[[3 0 4]
 [1 2 3]
 [0 1 2]
 [0 2 3]
 [3 1 0]
 [4 0 4]
 [3 2 2]
 [1 1 4]
 [3 1 4]
 [3 0 4]]
[[3 0 4]
 [1 2 3]
 [0 1 2]
 [0 2 3]
 [3 1 0]
 [4 0 4]
 [3 2 2]
 [1 1 4]
 [3 1 4]
 [3 0 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [73]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))


[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [74]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [51]:
A = np.array([1,2,3,4,5])
B = np.array([6,7,8,9,0])

print(np.einsum('i->', A)) # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B)) # np.inner(A, B)
print(np.einsum('i,j', A, B)) # np.outer(A, B)

15
[ 6 14 24 36  0]
80
[[ 6  7  8  9  0]
 [12 14 16 18  0]
 [18 21 24 27  0]
 [24 28 32 36  0]
 [30 35 40 45  0]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [78]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
[2.0, 0.0, 1.0, 1.0],
[1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [55]:
a= np.random.randn(10)
b = 100 
c = np.random.randint(0, a.size, (b, a.size))
means = a[c].mean(axis=1)
d = np.percentile(means, [97.5])
print(d)

[0.80440354]
